---
version: 2
build:
  os: "ubuntu-latest"
  tools:
    python: "3.10"
  apt_packages:
    - r-base
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
