---
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - plantuml
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip
  - epub
  - pdf
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
