---
version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  apt_packages:
    - r-base
    - pandoc
    - plantuml
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: requirements-docs.txt
    - path: .
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - docs
