---
version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  apt_packages:
    - r-base
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
# .readthedocs.yml
# python:
#   version: "3.10"
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - docs
