version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - plantuml
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip
  - pdf
  - epub
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
