version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - r-base
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
