include = ["**/*.toml"]

[formatting]
column_width = 60
align_comments = false
indent_string = "  "
compact_arrays = true
array_auto_expand = false
array_auto_collapse = false
inline_table_expand = false
